headsup:
  build: .
  command: php artisan serve --host=0.0.0.0 --port=8000
  volumes: 
    - .:/var/www/headsup
  ports:
    - "8000:8000"
  links:
    - headsupdb
  external_links:
     - webscraper_web_1:webscraper

headsupdb:
  image: mysql:5.6
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: "Z9T8kbZzP7Yahsu2"
    MYSQL_USER: "headsup"
    MYSQL_PASSWORD: "5hVfZ2bV5tBZdH88"
    MYSQL_DATABASE: "headsup"
    MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    MYSQL_RANDOM_ROOT_PASSWORD: "no"
